### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by ghost** [MrRobinOfficial/Guide-UnrealEngine#12]
Your `README.md` has an error:
```
To create a string builder with initialize buffer size:

int32 BufferSize = 12; // 12 characters of TCHAR
TStringBuilder<BufferSize> StringBuilder;
```

This is incorrect C++ code, **it does not compile**. You can't compile a template with an argument that's not known at compile time, like a `constexpr`. Either way, a constexpr doesn't provide a run-time dynamic size, so the code isn't helpful. You might as well have:
```
TStringBuilder<12> StringBuilder;
```

**Comment by MrRobinOfficial** [comment]
Yes, I fixed the issue. However, you wish to allocate at runtime, then use the base class `TStringBuilderBase` and specify your character type (`TCHAR`), like this:

`TStringBuilderBase<TCHAR> MessageBuilder;`

**Comment by ghost** [comment]
Hm, I'm looking at the issue on your README.md, and it's still very much there. Do you mean fixed locally, so it might be pushed to Github at a later time, or? I'm asking since I don't understand how you can say it's fixed when it's not. 
![image](https://github.com/user-attachments/assets/0394e0b0-58bb-4d42-bb22-22d929a6accc)

I attached what I'm looking at in your README.md, that doesn't compile. On both main and dev branches.

**Comment by MrRobinOfficial** [comment]
Yes, I fixed locally.

I'm also rewriting some other stuff. So, sorry for the delay.
Gonna publish the update later on.

Cheers,
Robin.
