### ISSUE TITLE
Consider replacing the word conjugation

### ISSUE THREAD

**Issue by elidoran** [MrRobinOfficial/Guide-UnrealEngine#2]
The word conjugation is used repeatedly like "This section was written in conjugation with ChatGPT."  Generally, "conjugate" means changing a verb based on tense. Like, "to walk" is walk, walking, walked. So, it doesn't seem to fit.

Sometimes the word "conjunction" is used when working together. So, it could be "This section was written in conjunction with ChatGPT."  It's still a little odd sounding. Perhaps the word "cooperation"?  As, "This section was written in cooperation with ChatGPT."  I suppose we don't "cooperate" with a computer service, only another person. Maybe use "This section was written with help from ChatGPT."

Up to you, of course. :)

**Comment by MrRobinOfficial** [comment]
Oh, sorry! I have noticed myself now, that I misspelled the word "conjunction" to "conjugation".

Will fix this in the future! Or I could change from "conjunction" to "help" instead (for better clarification).

**Comment by MrRobinOfficial** [comment]
Fixed with commit 0f0a9eb86675b17cd6cbcea3da1671241faed7b6
